// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const (
	TableNameRole        = "roles"
	TableNamePermission  = "permissions"
	TableNameUserRole    = "user_roles"
	TableNameRolePermission = "role_permissions"
)

// Role 角色表
type Role struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	Name        string    `gorm:"column:name;not null;comment:角色名称" json:"name"`                                      // 角色名称
	Description string    `gorm:"column:description;comment:角色描述" json:"description"`                                // 角色描述
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}

// Permission 权限表
type Permission struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	Name        string    `gorm:"column:name;not null;comment:权限名称" json:"name"`                                      // 权限名称
	Resource    string    `gorm:"column:resource;not null;comment:资源标识" json:"resource"`                              // 资源标识
	Action      string    `gorm:"column:action;not null;comment:操作标识" json:"action"`                                  // 操作标识
	Description string    `gorm:"column:description;comment:权限描述" json:"description"`                                // 权限描述
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}

// UserRole 用户角色关联表
type UserRole struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	UserID    int32     `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                  // 用户ID
	RoleID    int32     `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`                                  // 角色ID
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}

// RolePermission 角色权限关联表
type RolePermission struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	RoleID       int32     `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`                                  // 角色ID
	PermissionID int32     `gorm:"column:permission_id;not null;comment:权限ID" json:"permission_id"`                      // 权限ID
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}